2025-01-17 07:29:40,894 ERROR frappe New Exception collected with id: 2025-01-17 07:29:40.687245-127.0.0.1-093
Site: dcode.com
Form Dict: {}
2025-01-17 07:29:41,342 ERROR frappe New Exception collected with id: 2025-01-17 07:29:41.340760-127.0.0.1-29e
Site: dcode.com
Form Dict: {}
2025-01-17 07:29:42,341 ERROR frappe New Exception collected with id: 2025-01-17 07:29:42.339700-127.0.0.1-530
Site: dcode.com
Form Dict: {}
2025-01-17 07:29:42,374 ERROR frappe New Exception collected with id: 2025-01-17 07:29:42.373570-127.0.0.1-e81
Site: dcode.com
Form Dict: {}
2025-01-17 07:29:58,008 ERROR frappe New Exception collected with id: 2025-01-17 07:29:58.007652-127.0.0.1-cfd
Site: dcode.com
Form Dict: {}
2025-01-17 07:29:58,521 ERROR frappe New Exception collected with id: 2025-01-17 07:29:58.520445-127.0.0.1-b80
Site: dcode.com
Form Dict: {}
2025-01-17 07:29:58,684 ERROR frappe New Exception collected with id: 2025-01-17 07:29:58.683275-127.0.0.1-b4c
Site: dcode.com
Form Dict: {}
2025-01-17 07:29:58,691 ERROR frappe New Exception collected with id: 2025-01-17 07:29:58.690252-127.0.0.1-4e7
Site: dcode.com
Form Dict: {}
2025-01-17 07:35:37,039 ERROR frappe New Exception collected with id: 2025-01-17 07:35:36.803595-127.0.0.1-d80
Site: dcode.com
Form Dict: {}
2025-01-17 07:35:37,355 ERROR frappe New Exception collected with id: 2025-01-17 07:35:37.354445-127.0.0.1-e5d
Site: dcode.com
Form Dict: {}
2025-01-17 07:35:37,505 ERROR frappe New Exception collected with id: 2025-01-17 07:35:37.504693-127.0.0.1-29b
Site: dcode.com
Form Dict: {}
2025-01-17 07:35:37,529 ERROR frappe New Exception collected with id: 2025-01-17 07:35:37.527996-127.0.0.1-901
Site: dcode.com
Form Dict: {}
2025-01-17 07:35:45,224 ERROR frappe New Exception collected with id: 2025-01-17 07:35:45.223806-127.0.0.1-c50
Site: dcode.com
Form Dict: {}
2025-01-17 07:35:45,671 ERROR frappe New Exception collected with id: 2025-01-17 07:35:45.670355-127.0.0.1-dfa
Site: dcode.com
Form Dict: {}
2025-01-17 07:35:45,721 ERROR frappe New Exception collected with id: 2025-01-17 07:35:45.720584-127.0.0.1-5d3
Site: dcode.com
Form Dict: {}
2025-01-17 07:35:45,729 ERROR frappe New Exception collected with id: 2025-01-17 07:35:45.728307-127.0.0.1-3b5
Site: dcode.com
Form Dict: {}
2025-01-17 07:39:04,867 ERROR frappe New Exception collected with id: 2025-01-17 07:39:04.789376-127.0.0.1-f7a
Site: dcode.com
Form Dict: {}
2025-01-17 07:39:05,089 ERROR frappe New Exception collected with id: 2025-01-17 07:39:05.088471-127.0.0.1-9fb
Site: dcode.com
Form Dict: {}
2025-01-17 07:39:05,163 ERROR frappe New Exception collected with id: 2025-01-17 07:39:05.162485-127.0.0.1-8dc
Site: dcode.com
Form Dict: {}
2025-01-17 07:39:05,181 ERROR frappe New Exception collected with id: 2025-01-17 07:39:05.180643-127.0.0.1-898
Site: dcode.com
Form Dict: {}
2025-01-17 07:53:18,943 ERROR frappe New Exception collected with id: 2025-01-17 07:53:18.757875-127.0.0.1-dd3
Site: dcode.com
Form Dict: {}
2025-01-17 07:53:19,397 ERROR frappe New Exception collected with id: 2025-01-17 07:53:19.396047-127.0.0.1-4ed
Site: dcode.com
Form Dict: {}
2025-01-17 07:53:19,539 ERROR frappe New Exception collected with id: 2025-01-17 07:53:19.538079-127.0.0.1-c93
Site: dcode.com
Form Dict: {}
2025-01-17 07:53:19,559 ERROR frappe New Exception collected with id: 2025-01-17 07:53:19.558519-127.0.0.1-326
Site: dcode.com
Form Dict: {}
2025-01-17 07:59:40,527 ERROR frappe New Exception collected with id: 2025-01-17 07:59:40.437604-127.0.0.1-a76
Site: dcode.com
Form Dict: {}
2025-01-17 07:59:40,937 ERROR frappe New Exception collected with id: 2025-01-17 07:59:40.937023-127.0.0.1-7b9
Site: dcode.com
Form Dict: {}
2025-01-17 07:59:41,045 ERROR frappe New Exception collected with id: 2025-01-17 07:59:41.044501-127.0.0.1-a87
Site: dcode.com
Form Dict: {}
2025-01-17 07:59:41,064 ERROR frappe New Exception collected with id: 2025-01-17 07:59:41.063002-127.0.0.1-222
Site: dcode.com
Form Dict: {}
2025-01-17 08:04:33,188 ERROR frappe New Exception collected with id: 2025-01-17 08:04:32.992320-127.0.0.1-639
Site: dcode.com
Form Dict: {}
2025-01-17 08:04:33,745 ERROR frappe New Exception collected with id: 2025-01-17 08:04:33.744037-127.0.0.1-906
Site: dcode.com
Form Dict: {}
2025-01-17 08:04:33,807 ERROR frappe New Exception collected with id: 2025-01-17 08:04:33.806502-127.0.0.1-ade
Site: dcode.com
Form Dict: {}
2025-01-17 08:04:33,833 ERROR frappe New Exception collected with id: 2025-01-17 08:04:33.832305-127.0.0.1-26e
Site: dcode.com
Form Dict: {}
2025-01-17 08:20:43,336 ERROR frappe New Exception collected with id: 2025-01-17 08:20:43.107347-127.0.0.1-ed7
Site: dcode.com
Form Dict: {}
2025-01-17 08:20:43,908 ERROR frappe New Exception collected with id: 2025-01-17 08:20:43.907603-127.0.0.1-092
Site: dcode.com
Form Dict: {}
2025-01-17 08:20:44,028 ERROR frappe New Exception collected with id: 2025-01-17 08:20:44.027723-127.0.0.1-16d
Site: dcode.com
Form Dict: {}
2025-01-17 08:20:44,257 ERROR frappe New Exception collected with id: 2025-01-17 08:20:44.256937-127.0.0.1-17d
Site: dcode.com
Form Dict: {}
2025-01-17 08:28:19,040 ERROR frappe New Exception collected with id: 2025-01-17 08:28:18.859719-127.0.0.1-8a6
Site: dcode.com
Form Dict: {}
2025-01-17 08:28:19,294 ERROR frappe New Exception collected with id: 2025-01-17 08:28:19.293299-127.0.0.1-531
Site: dcode.com
Form Dict: {}
2025-01-17 08:28:19,513 ERROR frappe New Exception collected with id: 2025-01-17 08:28:19.511988-127.0.0.1-45c
Site: dcode.com
Form Dict: {}
2025-01-17 08:28:19,539 ERROR frappe New Exception collected with id: 2025-01-17 08:28:19.537992-127.0.0.1-9d9
Site: dcode.com
Form Dict: {}
2025-01-17 08:29:21,833 ERROR frappe New Exception collected with id: 2025-01-17 08:29:21.832888-127.0.0.1-dbc
Site: dcode.com
Form Dict: {}
2025-01-17 08:29:22,209 ERROR frappe New Exception collected with id: 2025-01-17 08:29:22.207845-127.0.0.1-e8a
Site: dcode.com
Form Dict: {}
2025-01-17 08:29:22,470 ERROR frappe New Exception collected with id: 2025-01-17 08:29:22.469236-127.0.0.1-e80
Site: dcode.com
Form Dict: {}
2025-01-17 08:29:22,673 ERROR frappe New Exception collected with id: 2025-01-17 08:29:22.672154-127.0.0.1-090
Site: dcode.com
Form Dict: {}
2025-01-17 08:29:23,260 ERROR frappe New Exception collected with id: 2025-01-17 08:29:23.259395-127.0.0.1-e54
Site: dcode.com
Form Dict: {}
2025-01-17 08:29:23,478 ERROR frappe New Exception collected with id: 2025-01-17 08:29:23.477389-127.0.0.1-aff
Site: dcode.com
Form Dict: {}
2025-01-17 08:29:23,803 ERROR frappe New Exception collected with id: 2025-01-17 08:29:23.802582-127.0.0.1-b03
Site: dcode.com
Form Dict: {}
2025-01-17 08:29:23,811 ERROR frappe New Exception collected with id: 2025-01-17 08:29:23.810153-127.0.0.1-a7d
Site: dcode.com
Form Dict: {}
2025-01-17 08:29:37,996 ERROR frappe New Exception collected with id: 2025-01-17 08:29:37.995299-127.0.0.1-b16
Site: dcode.com
Form Dict: {}
2025-01-17 08:29:38,417 ERROR frappe New Exception collected with id: 2025-01-17 08:29:38.416360-127.0.0.1-77d
Site: dcode.com
Form Dict: {}
2025-01-17 08:29:38,550 ERROR frappe New Exception collected with id: 2025-01-17 08:29:38.549255-127.0.0.1-b8a
Site: dcode.com
Form Dict: {}
2025-01-17 08:29:38,754 ERROR frappe New Exception collected with id: 2025-01-17 08:29:38.753063-127.0.0.1-d60
Site: dcode.com
Form Dict: {}
2025-01-17 08:30:55,312 ERROR frappe New Exception collected with id: 2025-01-17 08:30:55.311796-127.0.0.1-3f5
Site: dcode.com
Form Dict: {}
2025-01-17 08:30:55,792 ERROR frappe New Exception collected with id: 2025-01-17 08:30:55.791115-127.0.0.1-18d
Site: dcode.com
Form Dict: {}
2025-01-17 08:30:55,973 ERROR frappe New Exception collected with id: 2025-01-17 08:30:55.971882-127.0.0.1-de1
Site: dcode.com
Form Dict: {}
2025-01-17 08:30:56,195 ERROR frappe New Exception collected with id: 2025-01-17 08:30:56.194556-127.0.0.1-8b7
Site: dcode.com
Form Dict: {}
2025-01-17 08:34:23,790 ERROR frappe New Exception collected with id: 2025-01-17 08:34:23.789905-127.0.0.1-89b
Site: dcode.com
Form Dict: {}
2025-01-17 08:34:24,101 ERROR frappe New Exception collected with id: 2025-01-17 08:34:24.100747-127.0.0.1-003
Site: dcode.com
Form Dict: {}
2025-01-17 08:34:24,248 ERROR frappe New Exception collected with id: 2025-01-17 08:34:24.247557-127.0.0.1-2dd
Site: dcode.com
Form Dict: {}
2025-01-17 08:34:24,260 ERROR frappe New Exception collected with id: 2025-01-17 08:34:24.259091-127.0.0.1-a37
Site: dcode.com
Form Dict: {}
2025-01-17 08:48:41,857 ERROR frappe New Exception collected with id: 2025-01-17 08:48:41.618848-127.0.0.1-ca0
Site: dcode.com
Form Dict: {}
2025-01-17 08:48:42,148 ERROR frappe New Exception collected with id: 2025-01-17 08:48:42.147253-127.0.0.1-25e
Site: dcode.com
Form Dict: {}
2025-01-17 08:48:42,287 ERROR frappe New Exception collected with id: 2025-01-17 08:48:42.286388-127.0.0.1-94b
Site: dcode.com
Form Dict: {}
2025-01-17 08:48:42,315 ERROR frappe New Exception collected with id: 2025-01-17 08:48:42.313552-127.0.0.1-0ec
Site: dcode.com
Form Dict: {}
2025-01-17 08:54:13,778 ERROR frappe New Exception collected with id: 2025-01-17 08:54:13.777553-127.0.0.1-80b
Site: dcode.com
Form Dict: {}
2025-01-17 08:54:14,840 ERROR frappe New Exception collected with id: 2025-01-17 08:54:14.839827-127.0.0.1-a88
Site: dcode.com
Form Dict: {}
2025-01-17 08:54:14,905 ERROR frappe New Exception collected with id: 2025-01-17 08:54:14.904027-127.0.0.1-79d
Site: dcode.com
Form Dict: {}
2025-01-17 08:54:14,911 ERROR frappe New Exception collected with id: 2025-01-17 08:54:14.910575-127.0.0.1-cbf
Site: dcode.com
Form Dict: {}
2025-01-17 08:57:40,582 ERROR frappe New Exception collected with id: 2025-01-17 08:57:40.581687-127.0.0.1-666
Site: dcode.com
Form Dict: {}
2025-01-17 08:57:40,781 ERROR frappe New Exception collected with id: 2025-01-17 08:57:40.781154-127.0.0.1-3c6
Site: dcode.com
Form Dict: {}
2025-01-17 08:57:41,131 ERROR frappe New Exception collected with id: 2025-01-17 08:57:41.130320-127.0.0.1-dae
Site: dcode.com
Form Dict: {}
2025-01-17 08:57:41,140 ERROR frappe New Exception collected with id: 2025-01-17 08:57:41.139260-127.0.0.1-9fd
Site: dcode.com
Form Dict: {}
2025-01-17 08:58:08,734 ERROR frappe New Exception collected with id: 2025-01-17 08:58:08.733885-127.0.0.1-83d
Site: dcode.com
Form Dict: {}
2025-01-17 08:58:09,249 ERROR frappe New Exception collected with id: 2025-01-17 08:58:09.248440-127.0.0.1-fdd
Site: dcode.com
Form Dict: {}
2025-01-17 08:58:09,420 ERROR frappe New Exception collected with id: 2025-01-17 08:58:09.419651-127.0.0.1-34a
Site: dcode.com
Form Dict: {}
2025-01-17 08:58:09,458 ERROR frappe New Exception collected with id: 2025-01-17 08:58:09.457323-127.0.0.1-ac8
Site: dcode.com
Form Dict: {}
2025-01-17 08:59:24,099 ERROR frappe New Exception collected with id: 2025-01-17 08:59:24.098699-127.0.0.1-ea8
Site: dcode.com
Form Dict: {}
2025-01-17 08:59:24,507 ERROR frappe New Exception collected with id: 2025-01-17 08:59:24.506136-127.0.0.1-6d4
Site: dcode.com
Form Dict: {}
2025-01-17 08:59:24,575 ERROR frappe New Exception collected with id: 2025-01-17 08:59:24.574773-127.0.0.1-d7a
Site: dcode.com
Form Dict: {}
2025-01-17 08:59:24,585 ERROR frappe New Exception collected with id: 2025-01-17 08:59:24.583670-127.0.0.1-00c
Site: dcode.com
Form Dict: {}
2025-01-17 08:59:44,176 ERROR frappe New Exception collected with id: 2025-01-17 08:59:43.992750-127.0.0.1-d51
Site: dcode.com
Form Dict: {}
2025-01-17 08:59:44,681 ERROR frappe New Exception collected with id: 2025-01-17 08:59:44.680337-127.0.0.1-1f3
Site: dcode.com
Form Dict: {}
2025-01-17 08:59:44,945 ERROR frappe New Exception collected with id: 2025-01-17 08:59:44.944494-127.0.0.1-ac3
Site: dcode.com
Form Dict: {}
2025-01-17 08:59:45,178 ERROR frappe New Exception collected with id: 2025-01-17 08:59:45.177847-127.0.0.1-5dc
Site: dcode.com
Form Dict: {}
2025-01-17 14:15:20,168 ERROR frappe Failed to run after request hook
Site: dcode.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 649, in connect
    sock = socket.create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 86, in application
    init_request(request)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 177, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 38, in __init__
    self.set_session()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 118, in __init__
    self.make_session(resume=True)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 204, in make_session
    frappe.local.session_obj = Session(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 224, in __init__
    self.resume()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 303, in resume
    data = self.get_session_record()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 322, in get_session_record
    r = self.get_session_data()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 338, in get_session_data
    data = self.get_session_data_from_db()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 363, in get_session_data_from_db
    frappe.db.get_value(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '172.16.0.68' ([Errno 111] Connection refused)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 649, in connect
    sock = socket.create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 115, in application
    response = handle_exception(e)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 298, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 2289, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1109, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1200, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/document.py", line 76, in get_doc
    controller = get_controller(doctype)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in get_controller
    return _get_controller()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 61, in _get_controller
    module_name, custom = frappe.db.get_value(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '172.16.0.68' ([Errno 111] Connection refused)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 4335323603938858542

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 649, in connect
    sock = socket.create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 129, in application
    run_after_request_hooks(request, response)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 145, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1514, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1477, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1433, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 1056, in get_global
    return self.get_default(key, user)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 1060, in get_default
    d = self.get_defaults(key, parent)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 1076, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/defaults.py", line 238, in get_defaults_for
    frappe.qb.from_(table)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '172.16.0.68' ([Errno 111] Connection refused)")
2025-01-20 05:13:06,899 ERROR frappe Failed to run after request hook
Site: dcode.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 649, in connect
    sock = socket.create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 86, in application
    init_request(request)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 177, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 38, in __init__
    self.set_session()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 118, in __init__
    self.make_session(resume=True)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 204, in make_session
    frappe.local.session_obj = Session(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 224, in __init__
    self.resume()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 308, in resume
    self.validate_user()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 232, in validate_user
    if not frappe.get_cached_value("User", self.user, "enabled"):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1166, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1109, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1200, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/document.py", line 76, in get_doc
    controller = get_controller(doctype)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in get_controller
    return _get_controller()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 61, in _get_controller
    module_name, custom = frappe.db.get_value(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '172.16.0.68' ([Errno 111] Connection refused)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 649, in connect
    sock = socket.create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 115, in application
    response = handle_exception(e)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 298, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 2289, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1109, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1200, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/document.py", line 76, in get_doc
    controller = get_controller(doctype)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in get_controller
    return _get_controller()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 61, in _get_controller
    module_name, custom = frappe.db.get_value(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '172.16.0.68' ([Errno 111] Connection refused)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: -1082728930689305103

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 649, in connect
    sock = socket.create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 129, in application
    run_after_request_hooks(request, response)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 145, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1514, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1477, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1433, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 1056, in get_global
    return self.get_default(key, user)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 1060, in get_default
    d = self.get_defaults(key, parent)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 1076, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/defaults.py", line 238, in get_defaults_for
    frappe.qb.from_(table)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '172.16.0.68' ([Errno 111] Connection refused)")
2025-01-20 05:13:10,023 ERROR frappe Failed to run after request hook
Site: dcode.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 649, in connect
    sock = socket.create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 86, in application
    init_request(request)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 177, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 38, in __init__
    self.set_session()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 118, in __init__
    self.make_session(resume=True)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 204, in make_session
    frappe.local.session_obj = Session(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 224, in __init__
    self.resume()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 308, in resume
    self.validate_user()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 232, in validate_user
    if not frappe.get_cached_value("User", self.user, "enabled"):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1166, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1109, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1200, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/document.py", line 76, in get_doc
    controller = get_controller(doctype)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in get_controller
    return _get_controller()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 61, in _get_controller
    module_name, custom = frappe.db.get_value(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '172.16.0.68' ([Errno 111] Connection refused)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 649, in connect
    sock = socket.create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 115, in application
    response = handle_exception(e)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 298, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 2289, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1109, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1200, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/document.py", line 76, in get_doc
    controller = get_controller(doctype)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in get_controller
    return _get_controller()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 61, in _get_controller
    module_name, custom = frappe.db.get_value(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '172.16.0.68' ([Errno 111] Connection refused)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: -1082728930689305103

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 649, in connect
    sock = socket.create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 129, in application
    run_after_request_hooks(request, response)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 145, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1514, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1477, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1433, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 1056, in get_global
    return self.get_default(key, user)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 1060, in get_default
    d = self.get_defaults(key, parent)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 1076, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/defaults.py", line 238, in get_defaults_for
    frappe.qb.from_(table)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 716, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '172.16.0.68' ([Errno 111] Connection refused)")
2025-01-20 06:06:58,802 ERROR frappe Failed to run after request hook
Site: dcode.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 86, in application
    init_request(request)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 177, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 38, in __init__
    self.set_session()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 118, in __init__
    self.make_session(resume=True)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 204, in make_session
    frappe.local.session_obj = Session(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 224, in __init__
    self.resume()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 308, in resume
    self.validate_user()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 232, in validate_user
    if not frappe.get_cached_value("User", self.user, "enabled"):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1166, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1109, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1200, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/document.py", line 76, in get_doc
    controller = get_controller(doctype)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in get_controller
    return _get_controller()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 61, in _get_controller
    module_name, custom = frappe.db.get_value(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'firstErpDb'@'172.16.0.66' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 115, in application
    response = handle_exception(e)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 298, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 2289, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1109, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1200, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/document.py", line 76, in get_doc
    controller = get_controller(doctype)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in get_controller
    return _get_controller()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 61, in _get_controller
    module_name, custom = frappe.db.get_value(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'firstErpDb'@'172.16.0.66' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 580100366770351240

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 129, in application
    run_after_request_hooks(request, response)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 145, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1514, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1477, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1433, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 1056, in get_global
    return self.get_default(key, user)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 1060, in get_default
    d = self.get_defaults(key, parent)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 1076, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/defaults.py", line 238, in get_defaults_for
    frappe.qb.from_(table)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'firstErpDb'@'172.16.0.66' (using password: YES)")
2025-01-20 06:07:00,384 ERROR frappe Failed to run after request hook
Site: dcode.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 86, in application
    init_request(request)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 177, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 38, in __init__
    self.set_session()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 118, in __init__
    self.make_session(resume=True)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 204, in make_session
    frappe.local.session_obj = Session(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 224, in __init__
    self.resume()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 308, in resume
    self.validate_user()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 232, in validate_user
    if not frappe.get_cached_value("User", self.user, "enabled"):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1166, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1109, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1200, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/document.py", line 76, in get_doc
    controller = get_controller(doctype)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in get_controller
    return _get_controller()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 61, in _get_controller
    module_name, custom = frappe.db.get_value(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'firstErpDb'@'172.16.0.66' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 115, in application
    response = handle_exception(e)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 298, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 2289, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1109, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1200, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/document.py", line 76, in get_doc
    controller = get_controller(doctype)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in get_controller
    return _get_controller()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 61, in _get_controller
    module_name, custom = frappe.db.get_value(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'firstErpDb'@'172.16.0.66' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 580100366770351240

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 129, in application
    run_after_request_hooks(request, response)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 145, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1514, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1477, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1433, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 1056, in get_global
    return self.get_default(key, user)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 1060, in get_default
    d = self.get_defaults(key, parent)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 1076, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/defaults.py", line 238, in get_defaults_for
    frappe.qb.from_(table)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'firstErpDb'@'172.16.0.66' (using password: YES)")
2025-01-20 06:42:40,491 ERROR frappe Failed to run after request hook
Site: dcode.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 86, in application
    init_request(request)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 177, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 38, in __init__
    self.set_session()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 118, in __init__
    self.make_session(resume=True)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 204, in make_session
    frappe.local.session_obj = Session(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 224, in __init__
    self.resume()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 308, in resume
    self.validate_user()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 232, in validate_user
    if not frappe.get_cached_value("User", self.user, "enabled"):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1166, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1109, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1200, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/document.py", line 76, in get_doc
    controller = get_controller(doctype)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in get_controller
    return _get_controller()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 61, in _get_controller
    module_name, custom = frappe.db.get_value(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'firstErpDb'@'172.16.0.66' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 115, in application
    response = handle_exception(e)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 298, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 2289, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1109, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1200, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/document.py", line 76, in get_doc
    controller = get_controller(doctype)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in get_controller
    return _get_controller()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 61, in _get_controller
    module_name, custom = frappe.db.get_value(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'firstErpDb'@'172.16.0.66' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5877623335358744956

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 129, in application
    run_after_request_hooks(request, response)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 145, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1514, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1477, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1433, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 1056, in get_global
    return self.get_default(key, user)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 1060, in get_default
    d = self.get_defaults(key, parent)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 1076, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/defaults.py", line 238, in get_defaults_for
    frappe.qb.from_(table)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'firstErpDb'@'172.16.0.66' (using password: YES)")
2025-01-20 06:56:18,710 ERROR frappe Failed to run after request hook
Site: dcode.com
Form Dict: {}
Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 86, in application
    init_request(request)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 177, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 38, in __init__
    self.set_session()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 72, in set_session
    frappe.local.login_manager = LoginManager()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 118, in __init__
    self.make_session(resume=True)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/auth.py", line 204, in make_session
    frappe.local.session_obj = Session(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 224, in __init__
    self.resume()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 308, in resume
    self.validate_user()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/sessions.py", line 232, in validate_user
    if not frappe.get_cached_value("User", self.user, "enabled"):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1166, in get_cached_value
    doc = get_cached_doc(doctype, name)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1109, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1200, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/document.py", line 76, in get_doc
    controller = get_controller(doctype)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in get_controller
    return _get_controller()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 61, in _get_controller
    module_name, custom = frappe.db.get_value(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'firstErpDb'@'172.16.0.66' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 115, in application
    response = handle_exception(e)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 298, in handle_exception
    allow_traceback = frappe.get_system_settings("allow_error_traceback") if frappe.db else False
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 2289, in get_system_settings
    local.system_settings = get_cached_doc("System Settings")
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1109, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1200, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/document.py", line 76, in get_doc
    controller = get_controller(doctype)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in get_controller
    return _get_controller()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/model/base_document.py", line 61, in _get_controller
    module_name, custom = frappe.db.get_value(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 568, in get_value
    result = self.get_values(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 672, in get_values
    out = self._get_values_from_table(
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 910, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'firstErpDb'@'172.16.0.66' (using password: YES)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 5740354900026072187

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: -9027360110178035085

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 129, in application
    run_after_request_hooks(request, response)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/app.py", line 145, in run_after_request_hooks
    for after_request_task in frappe.get_hooks("after_request"):
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1514, in get_hooks
    hooks = _dict(cache().get_value("app_hooks", _load_app_hooks))
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/redis_wrapper.py", line 81, in get_value
    val = generator()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1477, in _load_app_hooks
    apps = [app_name] if app_name else get_installed_apps(_ensure_on_bench=True)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/__init__.py", line 1433, in get_installed_apps
    installed = json.loads(db.get_global("installed_apps") or "[]")
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 1056, in get_global
    return self.get_default(key, user)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 1060, in get_default
    d = self.get_defaults(key, parent)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 1076, in get_defaults
    defaults = frappe.defaults.get_defaults_for(parent)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/defaults.py", line 238, in get_defaults_for
    frappe.qb.from_(table)
  File "/home/abigael/frappe-bench/apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 221, in sql
    self.connect()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/database.py", line 126, in connect
    self._conn: "MariadbConnection" | "PostgresConnection" = self.get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 103, in get_connection
    conn = self._get_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 109, in _get_connection
    return self.create_connection()
  File "/home/abigael/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 112, in create_connection
    return pymysql.connect(**self.get_connection_settings())
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 361, in __init__
    self.connect()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 669, in connect
    self._request_authentication()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 957, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/abigael/frappe-bench/env/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'firstErpDb'@'172.16.0.66' (using password: YES)")
